error_log logs/error.log notice;

server {
    listen       8080;
    server_name  localhost;

    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    resolver local=on ipv6=off;
    access_by_lua_file jwt.lua;

    set_by_lua $sts_base_url 'return os.getenv("STS_BASE_URL")';
    set_by_lua $cics_base_url 'return os.getenv("CICS_BASE_URL")';

    # fjerner authorization slik at jwt-token ikke blir
    # sendt med nedover til de andre tjenestene
    proxy_set_header Proxy-Authorization  "";

    # simulering kan ta tid, så vi setter romslige timeouts
    proxy_connect_timeout 10s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;

    location / {
        add_header Content-Type text/plain;
        return 200;
    }

    location /sts/ {
        proxy_pass $sts_base_url;
        rewrite ^/sts/(.*) /$1 break;
    }

    location /cics/ {
        proxy_pass $cics_base_url;
        rewrite ^/cics/(.*) /$1 break;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/local/openresty/nginx/html;
    }
}
