name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Bygg image, push til github
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          tag: latest
          push_image: true
          pull: true
          dockerfile: Dockerfile
          docker_context: .
      - name: Post build failures to Slack
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Build av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.BAKS_DEPLOYMENTS_SLACK_WEBHOOK }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    name: Deploy to FSS
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v4
      - name: Deploy til dev-fss team namespace
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
      - name: Deploy til prod-fss team namespace
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/app-prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
      - name: Post deploy failures to Slack
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Deploy av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.BAKS_DEPLOYMENTS_SLACK_WEBHOOK }}
